"use client"

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { ScrollArea } from "@/components/ui/scroll-area"

interface LegalDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  type: "terms" | "privacy"
}

export function LegalDialog({ open, onOpenChange, type }: LegalDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold">
            {type === "terms" ? "Terms of Service" : "Privacy Policy"}
          </DialogTitle>
          <DialogDescription>
            Last updated: {new Date().toLocaleDateString()}
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] pr-4">
          {type === "terms" ? <TermsContent /> : <PrivacyContent />}
        </ScrollArea>
      </DialogContent>
    </Dialog>
  )
}

function TermsContent() {
  return (
    <div className="space-y-6 text-sm text-gray-700">
      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">1. Acceptance of Terms</h3>
        <p>
          By accessing and using Squpage ("the Service"), you accept and agree to be bound by the terms
          and provision of this agreement. If you do not agree to these Terms of Service, please do not
          use the Service.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">2. Description of Service</h3>
        <p>
          Squpage provides an AI-powered website builder platform that allows users to create, design,
          and publish websites. The Service includes access to templates, AI content generation, hosting,
          and related features.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">3. User Accounts</h3>
        <p className="mb-2">When you create an account with us, you must provide accurate and complete information. You are responsible for:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Maintaining the security of your account and password</li>
          <li>All activities that occur under your account</li>
          <li>Notifying us immediately of any unauthorized use</li>
        </ul>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">4. Acceptable Use</h3>
        <p className="mb-2">You agree not to use the Service to:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Violate any laws or regulations</li>
          <li>Infringe on intellectual property rights</li>
          <li>Distribute malware or harmful code</li>
          <li>Engage in spam or unauthorized advertising</li>
          <li>Harass, abuse, or harm others</li>
          <li>Impersonate any person or entity</li>
        </ul>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">5. Content Ownership</h3>
        <p>
          You retain all rights to the content you create using the Service. By using the Service, you
          grant Squpage a license to host, store, and display your content as necessary to provide the
          Service. We do not claim ownership of your content.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">6. AI-Generated Content</h3>
        <p>
          Content generated by our AI tools is provided as-is. You are responsible for reviewing and
          ensuring that AI-generated content meets your needs and complies with applicable laws before
          publishing.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">7. Payment and Billing</h3>
        <p>
          Some features of the Service may require payment. You agree to provide accurate billing
          information and authorize us to charge your payment method. Subscriptions automatically renew
          unless cancelled before the renewal date.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">8. Termination</h3>
        <p>
          We reserve the right to suspend or terminate your account at any time for violations of these
          Terms. You may cancel your account at any time through your account settings.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">9. Disclaimer of Warranties</h3>
        <p>
          The Service is provided "as is" without warranties of any kind, either express or implied. We
          do not guarantee that the Service will be uninterrupted, secure, or error-free.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">10. Limitation of Liability</h3>
        <p>
          To the maximum extent permitted by law, Squpage shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising from your use of the Service.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">11. Changes to Terms</h3>
        <p>
          We reserve the right to modify these Terms at any time. We will notify users of significant
          changes via email or through the Service. Continued use after changes constitutes acceptance of
          the new Terms.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">12. Contact Information</h3>
        <p>
          If you have any questions about these Terms, please contact us at support@squpage.com
        </p>
      </section>
    </div>
  )
}

function PrivacyContent() {
  return (
    <div className="space-y-6 text-sm text-gray-700">
      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">1. Information We Collect</h3>
        <p className="mb-2">We collect information you provide directly to us, including:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Account information (name, email, password)</li>
          <li>Profile information and preferences</li>
          <li>Content you create using our Service</li>
          <li>Payment and billing information</li>
          <li>Communications with our support team</li>
        </ul>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">2. Automatically Collected Information</h3>
        <p className="mb-2">When you use our Service, we automatically collect:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Device information (browser type, operating system)</li>
          <li>Usage data (pages viewed, features used, time spent)</li>
          <li>IP address and location data</li>
          <li>Cookies and similar tracking technologies</li>
        </ul>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">3. How We Use Your Information</h3>
        <p className="mb-2">We use the collected information to:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Provide, maintain, and improve our Service</li>
          <li>Process transactions and send related information</li>
          <li>Send technical notices and support messages</li>
          <li>Respond to your comments and questions</li>
          <li>Analyze usage patterns and optimize user experience</li>
          <li>Detect and prevent fraud and abuse</li>
          <li>Send marketing communications (with your consent)</li>
        </ul>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">4. Information Sharing</h3>
        <p className="mb-2">We may share your information with:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Service providers who assist in operating our platform</li>
          <li>Analytics partners to understand Service usage</li>
          <li>Law enforcement when required by law</li>
          <li>Other parties with your consent</li>
        </ul>
        <p className="mt-2">We do not sell your personal information to third parties.</p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">5. Data Security</h3>
        <p>
          We implement appropriate technical and organizational measures to protect your personal
          information. However, no method of transmission over the Internet is 100% secure, and we cannot
          guarantee absolute security.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">6. Data Retention</h3>
        <p>
          We retain your information for as long as your account is active or as needed to provide the
          Service. You may request deletion of your account and data at any time through your account
          settings.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">7. Your Rights</h3>
        <p className="mb-2">You have the right to:</p>
        <ul className="list-disc list-inside space-y-1 ml-4">
          <li>Access and receive a copy of your personal data</li>
          <li>Correct inaccurate or incomplete data</li>
          <li>Request deletion of your data</li>
          <li>Object to processing of your data</li>
          <li>Withdraw consent at any time</li>
          <li>Export your data in a portable format</li>
        </ul>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">8. Cookies and Tracking</h3>
        <p>
          We use cookies and similar technologies to collect usage data and improve our Service. You can
          control cookies through your browser settings, but disabling cookies may limit some
          functionality.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">9. Third-Party Services</h3>
        <p>
          Our Service may contain links to third-party websites or integrate with third-party services.
          We are not responsible for the privacy practices of these third parties. We encourage you to
          read their privacy policies.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">10. Children's Privacy</h3>
        <p>
          Our Service is not intended for children under 13 years of age. We do not knowingly collect
          personal information from children under 13. If you believe we have collected such information,
          please contact us immediately.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">11. International Data Transfers</h3>
        <p>
          Your information may be transferred to and processed in countries other than your own. We
          ensure appropriate safeguards are in place to protect your data in accordance with this Privacy
          Policy.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">12. Changes to Privacy Policy</h3>
        <p>
          We may update this Privacy Policy from time to time. We will notify you of significant changes
          by email or through a notice on our Service. Your continued use after changes indicates
          acceptance of the updated policy.
        </p>
      </section>

      <section>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">13. Contact Us</h3>
        <p>
          If you have questions about this Privacy Policy or our data practices, please contact us at
          privacy@squpage.com
        </p>
      </section>
    </div>
  )
}
