export const aiPhotoStudioConfig = {
  id: 'ai-photo-studio',
  name: 'AI Photo Studio',
  category: 'Creative',
  description: 'AI-powered photo studio and modelling agency landing page',
  thumbnail: '/ai-photo-studio-preview.png',
  editableFields: [
    { id: 'nav_logo', type: 'text', label: 'Logo Text', section: 'Navigation' },
    { id: 'nav_link_1', type: 'text', label: 'Nav Link', section: 'Navigation' },
    { id: 'nav_cta', type: 'button', label: 'Nav CTA', section: 'Navigation' },
    { id: 'hero_badge', type: 'text', label: 'Badge', section: 'Hero' },
    { id: 'hero_title_1', type: 'text', label: 'Title Line 1', section: 'Hero' },
    { id: 'hero_title_ampersand', type: 'text', label: 'Title Ampersand', section: 'Hero' },
    { id: 'hero_title_2', type: 'text', label: 'Title Line 2', section: 'Hero' },
    { id: 'hero_description', type: 'text', label: 'Description', section: 'Hero' },
    { id: 'hero_rating_text', type: 'text', label: 'Rating Text', section: 'Hero' },
    { id: 'hero_rating_score', type: 'text', label: 'Rating Score', section: 'Hero' },
    { id: 'hero_cta_primary', type: 'button', label: 'Primary CTA', section: 'Hero' },
    { id: 'hero_cta_secondary', type: 'button', label: 'Secondary CTA', section: 'Hero' },
    { id: 'hero_image', type: 'image', label: 'Hero Image', section: 'Hero' },
    { id: 'features_title', type: 'text', label: 'Section Title', section: 'Features' },
    { id: 'feature_1_title', type: 'text', label: 'Feature 1 Title', section: 'Features' },
    { id: 'feature_1_description', type: 'text', label: 'Feature 1 Description', section: 'Features' },
    { id: 'feature_1_image', type: 'image', label: 'Feature 1 Image', section: 'Features' },
    { id: 'feature_2_title', type: 'text', label: 'Feature 2 Title', section: 'Features' },
    { id: 'feature_2_description', type: 'text', label: 'Feature 2 Description', section: 'Features' },
    { id: 'feature_2_image', type: 'image', label: 'Feature 2 Image', section: 'Features' },
    { id: 'studio_title', type: 'text', label: 'Studio Title', section: 'Studio' },
    { id: 'studio_subtitle', type: 'text', label: 'Studio Subtitle', section: 'Studio' },
    { id: 'faq_title', type: 'text', label: 'FAQ Title', section: 'FAQ' },
    { id: 'faq_subtitle', type: 'text', label: 'FAQ Subtitle', section: 'FAQ' },
    { id: 'cta_title', type: 'text', label: 'CTA Title', section: 'CTA' },
    { id: 'cta_description', type: 'text', label: 'CTA Description', section: 'CTA' },
    { id: 'cta_button', type: 'button', label: 'CTA Button', section: 'CTA' },
    { id: 'footer_logo', type: 'text', label: 'Footer Logo', section: 'Footer' },
    { id: 'footer_description', type: 'text', label: 'Footer Description', section: 'Footer' },
    { id: 'footer_copyright', type: 'text', label: 'Copyright', section: 'Footer' },
  ],
} as const;

export type AIPhotoStudioConfig = typeof aiPhotoStudioConfig;
