export const catFoodConfig = {
  id: 'cat-food',
  name: 'Cat Food Product',
  category: 'E-commerce',
  description: 'Premium cat food product landing page with fresh and dry options',
  thumbnail: '/Cat Food Product Landing.png',
  editableFields: [
    { id: 'logo', type: 'text', label: 'Logo', section: 'Header' },
    { id: 'header_cta', type: 'button', label: 'Header CTA', section: 'Header' },
    { id: 'hero_title', type: 'text', label: 'Hero Title', section: 'Hero' },
    { id: 'hero_subtitle', type: 'text', label: 'Hero Subtitle', section: 'Hero' },
    { id: 'hero_cta', type: 'button', label: 'Hero CTA', section: 'Hero' },
    { id: 'hero_image', type: 'image', label: 'Hero Image', section: 'Hero' },
    { id: 'how_it_works_title', type: 'text', label: 'Section Title', section: 'How It Works' },
    { id: 'health_title', type: 'text', label: 'Health Title', section: 'Health' },
    { id: 'health_description', type: 'text', label: 'Health Description', section: 'Health' },
    { id: 'health_cta', type: 'button', label: 'Health CTA', section: 'Health' },
    { id: 'health_image', type: 'image', label: 'Health Image', section: 'Health' },
    { id: 'fresh_title', type: 'text', label: 'Fresh Food Title', section: 'Fresh Food' },
    { id: 'fresh_description', type: 'text', label: 'Fresh Food Description', section: 'Fresh Food' },
    { id: 'fresh_image', type: 'image', label: 'Fresh Food Image', section: 'Fresh Food' },
    { id: 'dry_title', type: 'text', label: 'Dry Food Title', section: 'Dry Food' },
    { id: 'dry_description', type: 'text', label: 'Dry Food Description', section: 'Dry Food' },
    { id: 'dry_image', type: 'image', label: 'Dry Food Image', section: 'Dry Food' },
    { id: 'benefits_title', type: 'text', label: 'Benefits Title', section: 'Benefits' },
    { id: 'benefit_image', type: 'image', label: 'Benefit Image', section: 'Benefits' },
    { id: 'testimonials_title', type: 'text', label: 'Testimonials Title', section: 'Testimonials' },
    { id: 'testimonials_cta', type: 'button', label: 'Testimonials CTA', section: 'Testimonials' },
    { id: 'guarantee_title', type: 'text', label: 'Guarantee Title', section: 'Guarantee' },
    { id: 'guarantee_description', type: 'text', label: 'Guarantee Description', section: 'Guarantee' },
  ],
} as const;

export type CatFoodConfig = typeof catFoodConfig;
